### ISSUE TITLE
How to use this package in bot v3

### ISSUE THREAD

**Issue by AkshayLokare** [ObjectivityLtd/Bot.Instrumentation#7]
Please provide some documentation or step to use this package in bot.

**Comment by piotrzajac** [comment]
Here you go
https://github.com/ObjectivityLtd/Bot.Instrumentation/tree/master/src/Bot.Instrumentation.V3

Please let us know in case you have troubles using it.

**Comment by AkshayLokare** [comment]
Thanks for reply
I know this one, but i am not getting where to add these code in luis bot.
I am new in this.

**Comment by AkshayLokare** [comment]
Hi @piotrzajac 
If you give any sample bot that is using this package, will help me lot.

Thanks in advance

**Comment by piotrzajac** [comment]
@AkshayLokare I've added the Getting Started section to the README under https://github.com/ObjectivityLtd/Bot.Instrumentation/tree/master/src/Bot.Instrumentation.V3

Basically what you need to do is to:
1. Ensure you have Application Insights created to obtain _Instrumentation Key_
2. Register `ActivityInstrumentation` and `DialogActivityLogger` in your application start code (usually Application_Start method in Global.asax.cs file)

Please let me know if you need further guidance.

**Comment by AkshayLokare** [comment]
Hi @piotrzajac ,

I registered ActivityInstrumentation and DialogActivityLogger in application insights, still i am not able to see any telemetry in application insights,
My application_start() code
protected void Application_Start()
        {
           
            TelemetryConfiguration.Active.InstrumentationKey = "***************************************";
            var telemetry = new TelemetryClient(TelemetryConfiguration.Active);
            var settings = new InstrumentationSettings();

            var builder = new ContainerBuilder();

            builder.RegisterModule(new AzureModule(Assembly.GetExecutingAssembly()));

            // Using Azure Table Storage
            var store = new TableBotDataStore(ConfigurationManager.AppSettings["AzureWebJobsStorage"]); // requires Microsoft.BotBuilder.Azure Nuget package 

            // To use CosmosDb or InMemory storage instead of the default table storage, uncomment the corresponding line below
            // var store = new DocumentDbBotDataStore("cosmos db uri", "cosmos db key"); // requires Microsoft.BotBuilder.Azure Nuget package 
            // var store = new InMemoryDataStore(); // volatile in-memory store

            builder.Register(c => store)
                .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                .AsSelf()
                .SingleInstance();

            builder.RegisterInstance(new ActivityInstrumentation(telemetry, settings))
           .Keyed<IIntentInstrumentation>(FiberModule.Key_DoNotSerialize)
           .As<IActivityInstrumentation>();

            builder.RegisterType<DialogActivityLogger>()
                   .AsImplementedInterfaces()
                   .InstancePerDependency();

            
            GlobalConfiguration.Configure(WebApiConfig.Register);
        }

**Comment by piotrzajac** [comment]
Instead of creating `ContainerBuilder` consider using the one from `Conversation`
```cs
protected void Application_Start()
{
    Conversation.UpdateContainer(builder =>
    {
        builder.RegisterModule(new AzureModule(Assembly.GetExecutingAssembly()));

        // Using Azure Table Storage
        var store = new TableBotDataStore(ConfigurationManager.AppSettings["AzureWebJobsStorage"]); // requires Microsoft.BotBuilder.Azure Nuget package 

        // To use CosmosDb or InMemory storage instead of the default table storage, uncomment the corresponding line below
        // var store = new DocumentDbBotDataStore("cosmos db uri", "cosmos db key"); // requires Microsoft.BotBuilder.Azure Nuget package 
        // var store = new InMemoryDataStore(); // volatile in-memory store

        builder.Register(c => store)
            .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
            .AsSelf()
            .SingleInstance();

        TelemetryConfiguration.Active.InstrumentationKey = "***************************************";
        var telemetry = new TelemetryClient(TelemetryConfiguration.Active);
        var settings = new InstrumentationSettings();

        builder.RegisterInstance(new ActivityInstrumentation(telemetry, settings))
           .Keyed<IIntentInstrumentation>(FiberModule.Key_DoNotSerialize)
           .As<IActivityInstrumentation>();

        builder.RegisterType<DialogActivityLogger>()
               .AsImplementedInterfaces()
               .InstancePerDependency();
    }

    
    GlobalConfiguration.Configure(WebApiConfig.Register);
}
```

You should see `customEvents` in Application Insights. Here is a simple query to find out if they appear
```sql
customEvents 
| where name startswith "MBFEvent"
```

**Comment by AkshayLokare** [comment]
@piotrzajac ,Initially i try same thing but i got following error,

System.ArgumentException: 'The type 'Bot.Instrumentation.V3.Instrumentations.ActivityInstrumentation' is not assignable to service 'System.Object (Bot.Instrumentation.V3.Instrumentations.IIntentInstrumentation)'.'


Thanks

**Comment by piotrzajac** [comment]
There was an issue in the original code.
```cs
builder.RegisterInstance(new ActivityInstrumentation(telemetry, settings))
   .Keyed<IIntentInstrumentation>(FiberModule.Key_DoNotSerialize)
   .As<IActivityInstrumentation>();
```
Since the `IActivityInstrumentation` is being registered the `IIntentInstrumentation` should not be specified in `Keyed<T>()` method.

I've already fixed my previous comment.

Please let me know if it works for you.

**Comment by piotrzajac** [comment]
Closing because of lack of response.
